# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='gallery title', max_length=100, verbose_name='title')),
                ('slug', models.SlugField(help_text='url name', max_length=110, verbose_name='slug')),
                ('zip_import', models.FileField(help_text='upload zip file containing images', upload_to='galleries', verbose_name='zip import')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'verbose_name': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='galleries')),
                ('description', models.CharField(blank=True, help_text='leave blank to autogenerate from image name', max_length=400, verbose_name='description')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zipgallery.Gallery')),
            ],
            options={
                'verbose_name_plural': 'images',
                'verbose_name': 'image',
            },
        ),
    ]
